syncfusion-content/ej2-schedule-docs

schedule/ej2-javascript-schedule-toc.html
schedule/ej2-typescript-schedule-toc.html

documentation(EJ2-71943): toc changed

---

schedule/ej2-typescript-schedule-toc.html

documentation(EJ2-71943): fixed toc issues

---

schedule/ej2-typescript-schedule-toc.html

documentation(EJ2-71943): changed toc structure

---

ej2-javascript/schedule/localization.md

Documentation(833299): Fixed Broken link issue

---

ej2-javascript/schedule/state-persistence.md

Resolved the broken links issues in Schedule documentation.
Resolved the broken links in State persistence topic
NA
No area is affected due to this changes.
NA
NA
* Did you run the automation against your implementation? NA
* Is there any API name change? No
* Is there any existing behavior change of other features due to this code change? No
* Does your new code introduce new warnings or binding errors? No
* Does your code pass all FxCop and StyleCop rules? Yes
* Did you record this case in the unit test or UI test? NA

documentation(839526): Resolved broken links issues in Schedule documentation

---

ej2-javascript/schedule/state-persistence.md

Resolved broken link issue for schedule component

bug(839526): Resolved broken link issue for schedule component

---

ej2-javascript/schedule/editor-template.md

Include note section for e-field in custom event editor using template for typescript and javascript platform

Documentation(ES-841586) : To include note section for e-field in custom event editor using template for typescript and javascript platform

---

ej2-javascript/schedule/timescale.md

To include note section about the timescale restrictions for typescript and javascript platforms
NA
NA

Documentation(ES-820305): To include note section about the timescale restrictions for typescript and javascript platforms

---

ej2-javascript/schedule/how-to/salesforce-integration.md

description:
clear the failures.
Areas affected and ensured:
Test cases:
NA
Test bed sample location:
NA
Additional checklist

documentation(ES-843760-resolvebuildErrors): Clear the ug failures.

---

ej2-javascript/code-snippet/schedule/lazy-loading-cs1/index.css
ej2-javascript/code-snippet/schedule/lazy-loading-cs1/index.js
ej2-javascript/code-snippet/schedule/lazy-loading-cs1/index.ts
ej2-javascript/code-snippet/schedule/lazy-loading-cs1/js/index.html
ej2-javascript/code-snippet/schedule/lazy-loading-cs1/systemjs.config.js
ej2-javascript/code-snippet/schedule/lazy-loading-cs1/ts/index.html
ej2-javascript/schedule/virtual-scrolling.md

UG included for lazy loading feature

docs(ES-378260): UG included for lazy loading feature

---

ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/index.css
ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/index.js
ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/index.ts
ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/js/index.html
ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/systemjs.config.js
ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/ts/index.html
ej2-javascript/schedule/editor-template.md

Include UG for editor header and footer in javascript and typescript.

Documentation(ES-845513): Include UG for editor header and footer.

---

ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/systemjs.config.js

resolved script error for editor header and footer template.

Documentation(ES-845513): resolved script error for editor header and footer template.

---

ej2-javascript/schedule/how-to/salesforce-integration.md

Need to resolve resolved UG publishing failures.
We have not verified syntax and tags that are closed properly.
Find how it was missed in our earlier testing and development by analyzing the below checklist. This will help prevent similar mistakes in the future. 
- Specification document
- Requirement document
- Common guidelines / Core team guideline
- Specification document
- Requirement document
We have not checked and ensured locally for the syntax and tags that are placed properly.
Verified the syntax were placed properly and Tags were created and closed properly on the document.
Need to ensure the visual content of the Documentation. 
No
We have fixed this issue via adjusting the syntax and tag content of the document that are placed properly.
Ensured the EJ2 Vue documentation.
- …

bug(849798): Need to resolve resolved UG publishing failures

---

ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/systemjs.config.js
ej2-javascript/schedule/editor-template.md

description:
resolve conflict in schedule docs.

documentation(ES-836547-ConflictFile): Resolve conflict in schedule docs.

---

ej2-javascript/schedule/how-to/salesforce-integration.md

Description:
Content modify in salesforce topic in javascript docs.

documentation(ES-836547-contentModify): content modify in schedule docs.

---

ej2-javascript/code-snippet/schedule/resource-grouping-cs5/index.js
ej2-javascript/schedule/resources.md

Collapse/Expand child resources in timeline views preview sample issue resolved and content modified for javascript platform
NA
NA

documentation(ES-379127): Collapse/Expand child resources in timeline views preview sample issue resolved and content modified for javascript platform

---

ej2-javascript/code-snippet/schedule/data-bind-cs7/index.js
ej2-javascript/code-snippet/schedule/data-bind-cs7/index.ts
ej2-javascript/code-snippet/schedule/recur-editor-cs3/index.js
ej2-javascript/code-snippet/schedule/recur-editor-cs3/index.ts
ej2-javascript/code-snippet/schedule/view-cs18/index.js
ej2-javascript/code-snippet/schedule/view-cs18/index.ts

Cleared the preview sample issues for our schedule samples in typescript and javascript platform
NA
NA

documentation(ES-852376): Cleared the preview sample issues for our schedule samples in typescript and javascript platform

---

ej2-javascript/schedule/js/frequently-asked-questions.md
ej2-javascript/schedule/ts/frequently-asked-questions.md

Added topic in FAQ of Scheduler about getting instance of the scheduler.
NA
NA

Documentation(ES-378937): Added topic in FAQ of Scheduler about getting instance of the scheduler.

---

ej2-javascript/schedule/data-binding.md
ej2-javascript/schedule/how-to/salesforce-integration.md

Salesforce integration reference link updated

docs(ES-852877): Salesforce integration reference link updated

---

ej2-javascript/schedule/appointments.md
ej2-javascript/schedule/cell-customization.md

Update the restriction details about isSlotAvailable method in typescript and javascript platform
NA
NA

documentation(ES-640354): Update the restriction details about isSlotAvailable method in typescript and javascript platform

---

ej2-javascript/schedule/js/getting-started.md
ej2-javascript/schedule/ts/getting-started.md

Description;
Resolve the getting started sample issues.

documentation(ES-853828-gettingStarted): Resolve getting started issues in ts and js schedule docs.

---

ej2-javascript/code-snippet/schedule/header-bar-template/datasource.ts
ej2-javascript/code-snippet/schedule/header-bar-template/es5-datasource.js
ej2-javascript/code-snippet/schedule/header-bar-template/index.css
ej2-javascript/code-snippet/schedule/header-bar-template/index.html
ej2-javascript/code-snippet/schedule/header-bar-template/index.js
ej2-javascript/code-snippet/schedule/header-bar-template/index.ts
ej2-javascript/code-snippet/schedule/header-bar-template/js/index.html
ej2-javascript/code-snippet/schedule/header-bar-template/systemjs.config.js
ej2-javascript/code-snippet/schedule/header-bar-template/ts/index.html
ej2-javascript/schedule/header-bar.md

Added the custom toolbar sample in UG documentation.
Areas affected and ensured:
Header bar customization
**Output:**
Test cases:
NA
Test bed sample location:
NA
Additional checklist

documentation(ES-859785-custom-toolbar): Added the custom toolbar sample in schedule docs.

---

ej2-javascript/schedule/accessibility.md

Improve accessibility topic and hyperlink changed in ts and js schedule docs.

documentation(ES-864834-ImproveAccessibility): Improve accessibility topic and hyperlink changed in ts and js docs.

---

ej2-javascript/code-snippet/schedule/header-bar-template/index.js
ej2-javascript/code-snippet/schedule/header-bar-template/index.ts
ej2-javascript/code-snippet/schedule/view-cs19/index.js
ej2-javascript/code-snippet/schedule/view-cs19/index.ts

**Description**:
changes updated in newly feature sample like maxEventsPerRow and custom toolbar sample.

documentation(ES-864834-SampleCorrections): Correction in New added feature sample.

---

ej2-javascript/schedule/accessibility.md

Review correction in accessibility topic in schedule ts and js documentation.

documentation(ES-864834-reviewCorrection): Review correction in schedule docs.

---

ej2-javascript/schedule/accessibility.md

Need to modified the icons on accessibility document. The Icons are newly created for the compilance measuring.
[866555](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/866555)
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes got approval if UI is …

866555: Need to modified the icons on accessibility document

---

ej2-javascript/schedule/crud-actions.md

Hi @MallikaRK,
please review the changes made.
Thanks.
Regards,
Edith.

SEO-178901-ej2-js-schedule-page-with-redirect-link

---

ej2-javascript/code-snippet/schedule/weekend-cell-color/datasource.ts
ej2-javascript/code-snippet/schedule/weekend-cell-color/es5-datasource.js
ej2-javascript/code-snippet/schedule/weekend-cell-color/index.css
ej2-javascript/code-snippet/schedule/weekend-cell-color/index.js
ej2-javascript/code-snippet/schedule/weekend-cell-color/index.ts
ej2-javascript/code-snippet/schedule/weekend-cell-color/js/index.html
ej2-javascript/code-snippet/schedule/weekend-cell-color/systemjs.config.js
ej2-javascript/code-snippet/schedule/weekend-cell-color/ts/index.html
ej2-javascript/schedule/cell-customization.md

**Description**:
Added the topic for weekend cell customization in Scheduler
**Areas affected and ensured**:
Cell Customizations
**Test cases**:
NA
**Test bed sample location**:
NA
**Additional checklist**:

Documentation(ES-379228): Added the topic for weekend cell customization in Scheduler

---

ej2-javascript/schedule/localization.md

Hi @MallikaRK ,
Worked on js scheduler changes.
Regards,
Sharly A.

SEO-180850-JS-Scheduler-Changes
